
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/security;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
  port: 9090

