
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring_security
    username: root
    password: 11111

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
  port: 9090

